//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample4.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoDeCuenta
    {
        public int ID { get; set; }
        public string Cuenta { get; set; }
        public Nullable<decimal> Entrada { get; set; }
        public Nullable<decimal> Salida { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Nonce { get; set; }
        public string Hash { get; set; }
    }
}
